version: '3'
services:

  block-producers-directory-front:
    container_name: block-producers-directory-front
    build:
      context: .
      dockerfile: Dockerfile.development
    command: npm run serve
    volumes:
      - ./src:/block-producers-directory-front/src
    environment:
      - 'BACK_END_URL=https://bps-directory-back-staging.herokuapp.com'
    ports:
      - '8080:8080'
